### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_registry2#35]
### Stage 1

- [ ] Track download counts
- [ ] Display download counts on website as a graph (like crates.io)
- [ ] Run `deno info --json` on ts/js files in the repository to get a dependency graph. Store in `$NAME/versions/$VERSION/meta/deps.json`. This tree should be a multi entry point graph with nodes and edges, not a simple tree.

### Stage 2

- [ ] Run `deno fmt` on all files in repo and store list of failed files in `$NAME/versions/$VERSION/meta/analysis.json`
- [ ] Run `deno lint --json` on all files in repo and store list of failed files + the diagnostics in `$NAME/versions/$VERSION/meta/analysis.json`
- [ ] Run `deno check` on all files in repo and store list of failed files in `$NAME/versions/$VERSION/meta/analysis.json`
- [ ] Run other checks on repository (`LICENCE` & `README.md` file there, are dependencies pinned to specific version) and store this in `$NAME/versions/$VERSION/meta/analysis.json`.

### Stage 3

- [ ] Run `deno doc --json` on all files in the repo and store the output in `$NAME/versions/$VERSION/docs/$FILEPATH.json`
- [ ] Create & store a type stripped stripped version of all files in `$NAME/versions/$VERSION/stripped/$FILEPATH.json`

**Comment by brandonkal** [comment]
Please ensure Stage 2 is opt-in for the module author. Also, a `deno fmt` report provides no value-add for the library consumer and will only generate noise.

**Comment by nayeemrmn** [comment]
> Please ensure Stage 2 is opt-in for the module author.

That kind of destroys the point...

**Comment by brandonkal** [comment]
If it is not opt-in it will generate too much noise.
1. deno check will fail if parts of the code need to run with `--unstable`. I can document that in the README, but some automated scan will mark the module as bad. Just another false-positive.
2. Are you going to mark modules as bad because it uses tabs or prettier instead? That's nonsense. `deno fmt` output is entirely subjective and has no bearing on the usability of code.
3. deno lint is also subjective as well.

These are a few reasons why making any automated checks opt-in.

**Comment by littledivy** [comment]
The frequency at which a module is updated should be considered as well?

**Comment by jhechtf** [comment]
For the Gitlab / Bitbucket integration, what needs to be done to move those forward?
