### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_registry2#8]
This is a summary of things that need to be done for the initial release:

- [x] Validate requests coming from GitHub (#7)
- [x] Search API (#11)
- [x] base `path` parameter (required for std) (#12)
- [x] Get `std` working (version prefix) (#13)
- [x] Upload all `database.json` modules with all released versions as a batch job
- [x] Setup Cloudflare to proxy `api.deno.land` to the AWS API Gateway domain
- [x] Add limits (#19)
